# Generated by Django 3.0.2 on 2020-05-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200510_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='inf',
            new_name='informations',
        ),
    ]
