# Generated by Django 3.0.2 on 2020-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200513_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_phone_number',
            field=models.IntegerField(),
        ),
    ]
